WhichTheme.register({
  id: 'moonfly',
  name: 'Moonfly',
  group: 'Moonfly',
  homepage: 'https://github.com/bluz71/vim-moonfly-colors',
  preview: {
    bg: '#080808', bg2: '#323437', text: '#bdbdbd', comment: '#4e4e4e',
    keyword: '#ff5454', func: '#82aaff', string: '#e3c78a', number: '#cf87e8',
    operator: '#57c7ff', type: '#36c692', highlight: '#1c1c1c',
  },
  colors: [
    { name: 'Black',       hex: '#080808' },
    { name: 'Dark Gray',   hex: '#323437' },
    { name: 'Charcoal',    hex: '#444444' },
    { name: 'Gray',        hex: '#4e4e4e' },
    { name: 'Medium Gray', hex: '#6e7070' },
    { name: 'Cadet',       hex: '#8b9cbe' },
    { name: 'Off-White',   hex: '#bdbdbd' },
    { name: 'White',       hex: '#c6c6c6' },
    { name: 'Red',         hex: '#ff5454' },
    { name: 'Watermelon',  hex: '#ff6e9e' },
    { name: 'Orange',      hex: '#e65e72' },
    { name: 'Yellow',      hex: '#e3c78a' },
    { name: 'Khaki',       hex: '#c6c886' },
    { name: 'Lime',        hex: '#85dc85' },
    { name: 'Emerald',     hex: '#36c692' },
    { name: 'Turquoise',   hex: '#57c7ff' },
    { name: 'Blue',        hex: '#82aaff' },
    { name: 'Violet',      hex: '#ae81ff' },
    { name: 'Purple',      hex: '#cf87e8' },
    { name: 'Crimson',     hex: '#d23e65' },
    { name: 'Pink',        hex: '#ff5ea0' },
  ],
});
