WhichTheme.register({
  id: 'gruvbox-dark',
  name: 'Gruvbox Dark',
  group: 'Gruvbox',
  homepage: 'https://github.com/morhetz/gruvbox',
  preview: {
    bg: '#282828', bg2: '#1d2021', text: '#ebdbb2', comment: '#928374',
    keyword: '#fb4934', func: '#b8bb26', string: '#b8bb26', number: '#d3869b',
    operator: '#8ec07c', type: '#83a598', highlight: '#3c3836',
  },
  colors: [
    { name: 'Background',      hex: '#282828' },
    { name: 'Background Hard', hex: '#1d2021' },
    { name: 'Background Soft', hex: '#32302f' },
    { name: 'Background 1',    hex: '#3c3836' },
    { name: 'Background 2',    hex: '#504945' },
    { name: 'Background 3',    hex: '#665c54' },
    { name: 'Background 4',    hex: '#7c6f64' },
    { name: 'Foreground',      hex: '#ebdbb2' },
    { name: 'Foreground 1',    hex: '#d5c4a1' },
    { name: 'Foreground 2',    hex: '#bdae93' },
    { name: 'Foreground 3',    hex: '#a89984' },
    { name: 'Red',             hex: '#cc241d' },
    { name: 'Red Bright',      hex: '#fb4934' },
    { name: 'Green',           hex: '#98971a' },
    { name: 'Green Bright',    hex: '#b8bb26' },
    { name: 'Yellow',          hex: '#d79921' },
    { name: 'Yellow Bright',   hex: '#fabd2f' },
    { name: 'Blue',            hex: '#458588' },
    { name: 'Blue Bright',     hex: '#83a598' },
    { name: 'Purple',          hex: '#b16286' },
    { name: 'Purple Bright',   hex: '#d3869b' },
    { name: 'Aqua',            hex: '#689d6a' },
    { name: 'Aqua Bright',     hex: '#8ec07c' },
    { name: 'Orange',          hex: '#d65d0e' },
    { name: 'Orange Bright',   hex: '#fe8019' },
  ],
});
