WhichTheme.register({
  id: 'gruvbox-light',
  name: 'Gruvbox Light',
  group: 'Gruvbox',
  homepage: 'https://github.com/morhetz/gruvbox',
  preview: {
    bg: '#fbf1c7', bg2: '#f9f5d7', text: '#3c3836', comment: '#7c6f64',
    keyword: '#9d0006', func: '#79740e', string: '#79740e', number: '#8f3f71',
    operator: '#427b58', type: '#076678', highlight: '#ebdbb2',
  },
  colors: [
    { name: 'Background',      hex: '#fbf1c7' },
    { name: 'Background Hard', hex: '#f9f5d7' },
    { name: 'Background Soft', hex: '#f2e5bc' },
    { name: 'Background 1',    hex: '#ebdbb2' },
    { name: 'Background 2',    hex: '#d5c4a1' },
    { name: 'Background 3',    hex: '#bdae93' },
    { name: 'Background 4',    hex: '#a89984' },
    { name: 'Foreground',      hex: '#3c3836' },
    { name: 'Foreground 1',    hex: '#504945' },
    { name: 'Foreground 2',    hex: '#665c54' },
    { name: 'Foreground 3',    hex: '#7c6f64' },
    { name: 'Red',             hex: '#9d0006' },
    { name: 'Red Bright',      hex: '#cc241d' },
    { name: 'Green',           hex: '#79740e' },
    { name: 'Green Bright',    hex: '#98971a' },
    { name: 'Yellow',          hex: '#b57614' },
    { name: 'Yellow Bright',   hex: '#d79921' },
    { name: 'Blue',            hex: '#076678' },
    { name: 'Blue Bright',     hex: '#458588' },
    { name: 'Purple',          hex: '#8f3f71' },
    { name: 'Purple Bright',   hex: '#b16286' },
    { name: 'Aqua',            hex: '#427b58' },
    { name: 'Aqua Bright',     hex: '#689d6a' },
    { name: 'Orange',          hex: '#af3a03' },
    { name: 'Orange Bright',   hex: '#d65d0e' },
  ],
});
