WhichTheme.register({
  id: 'poimandres',
  name: 'Poimandres',
  group: 'Poimandres',
  homepage: 'https://github.com/olivercederborg/poimandres.nvim',
  preview: {
    bg: '#1b1e28', bg2: '#252837', text: '#a6accd', comment: '#767c9d',
    keyword: '#5de4c7', func: '#add7ff', string: '#f1da98', number: '#5de4c7',
    operator: '#89ddff', type: '#add7ff', highlight: '#2b3043',
  },
  colors: [
    { name: 'Background',  hex: '#1b1e28' },
    { name: 'Surface',     hex: '#252837' },
    { name: 'Overlay',     hex: '#303340' },
    { name: 'Muted High',  hex: '#3d3f4f' },
    { name: 'Muted',       hex: '#535771' },
    { name: 'Subtle',      hex: '#767c9d' },
    { name: 'Text',        hex: '#a6accd' },
    { name: 'White',       hex: '#e4f0fb' },
    { name: 'Pink',        hex: '#d0679d' },
    { name: 'Flamingo',    hex: '#e58ac9' },
    { name: 'Teal',        hex: '#5de4c7' },
    { name: 'Cyan',        hex: '#89ddff' },
    { name: 'Blue',        hex: '#add7ff' },
    { name: 'Blue Dim',    hex: '#91b4d5' },
    { name: 'Cream',       hex: '#f1da98' },
    { name: 'Yellow Dim',  hex: '#fffac2' },
  ],
});
