WhichTheme.register({
  id: 'gruvbox-material-light',
  name: 'Gruvbox Material Light',
  group: 'Gruvbox Material',
  homepage: 'https://github.com/sainnhe/gruvbox-material',
  preview: {
    bg: '#fbf1c7', bg2: '#f9f5d7', text: '#654735', comment: '#a89984',
    keyword: '#c14a4a', func: '#45707a', string: '#6c782e', number: '#945e80',
    operator: '#4c7a5d', type: '#45707a', highlight: '#ebdbb2',
  },
  colors: [
    { name: 'Background',      hex: '#fbf1c7' },
    { name: 'Background Hard', hex: '#f9f5d7' },
    { name: 'Background Soft', hex: '#f2e5bc' },
    { name: 'Background 1',    hex: '#ebdbb2' },
    { name: 'Background 2',    hex: '#d5c4a1' },
    { name: 'Background 3',    hex: '#bdae93' },
    { name: 'Background 4',    hex: '#a89984' },
    { name: 'Gray',            hex: '#928374' },
    { name: 'Foreground',      hex: '#654735' },
    { name: 'Red',             hex: '#c14a4a' },
    { name: 'Orange',          hex: '#c35e0a' },
    { name: 'Yellow',          hex: '#b47109' },
    { name: 'Green',           hex: '#6c782e' },
    { name: 'Aqua',            hex: '#4c7a5d' },
    { name: 'Blue',            hex: '#45707a' },
    { name: 'Purple',          hex: '#945e80' },
  ],
});
