WhichTheme.register({
  id: 'nightfly',
  name: 'Nightfly',
  group: 'Nightfly',
  homepage: 'https://github.com/bluz71/vim-nightfly-colors',
  preview: {
    bg: '#011627', bg2: '#01111d', text: '#d6deeb', comment: '#637777',
    keyword: '#c792ea', func: '#82aaff', string: '#ecc48d', number: '#f78c6c',
    operator: '#7fdbca', type: '#c3e88d', highlight: '#1d3b53',
  },
  colors: [
    { name: 'Black',       hex: '#011627' },
    { name: 'Dark Blue',   hex: '#01111d' },
    { name: 'Deep Blue',   hex: '#0e2942' },
    { name: 'Regal Blue',  hex: '#123262' },
    { name: 'Slate Blue',  hex: '#1d3b53' },
    { name: 'Pickle Blue', hex: '#1e4673' },
    { name: 'Steel Blue',  hex: '#4b6479' },
    { name: 'Grey Blue',   hex: '#7c8f8f' },
    { name: 'Cadet Blue',  hex: '#a1aab8' },
    { name: 'White Blue',  hex: '#d6deeb' },
    { name: 'Red',         hex: '#ff5874' },
    { name: 'Watermelon',  hex: '#ff6e9e' },
    { name: 'Orange',      hex: '#f78c6c' },
    { name: 'Yellow',      hex: '#e3d18a' },
    { name: 'Tan',         hex: '#ecc48d' },
    { name: 'Green',       hex: '#c3e88d' },
    { name: 'Emerald',     hex: '#21c7a8' },
    { name: 'Turquoise',   hex: '#7fdbca' },
    { name: 'Blue',        hex: '#82aaff' },
    { name: 'Violet',      hex: '#c792ea' },
    { name: 'Lavender',    hex: '#b0c9f0' },
  ],
});
