WhichTheme.register({
  id: 'kanagawa-lotus',
  name: 'Kanagawa Lotus',
  group: 'Kanagawa',
  homepage: 'https://github.com/rebelot/kanagawa.nvim',
  preview: {
    bg: '#f2ecbc', bg2: '#e7dba0', text: '#545464', comment: '#8a8980',
    keyword: '#c84053', func: '#4d699b', string: '#6f894e', number: '#cc6d00',
    operator: '#4e8ca2', type: '#5d57a3', highlight: '#f4f3f0',
  },
  colors: [
    { name: 'Background',      hex: '#f2ecbc' },
    { name: 'Background Dark', hex: '#e7dba0' },
    { name: 'Lotus Ink 1',     hex: '#545464' },
    { name: 'Lotus Ink 2',     hex: '#43436c' },
    { name: 'Fuji Gray',       hex: '#727169' },
    { name: 'Lotus Red',       hex: '#c84053' },
    { name: 'Lotus Red 2',     hex: '#d7474b' },
    { name: 'Lotus Pink',      hex: '#b35b79' },
    { name: 'Lotus Orange',    hex: '#cc6d00' },
    { name: 'Lotus Orange 2',  hex: '#e98a00' },
    { name: 'Lotus Yellow',    hex: '#77713f' },
    { name: 'Lotus Yellow 3',  hex: '#de9800' },
    { name: 'Lotus Green',     hex: '#6f894e' },
    { name: 'Lotus Green 2',   hex: '#6e915f' },
    { name: 'Lotus Teal 1',    hex: '#4e8ca2' },
    { name: 'Lotus Teal 2',    hex: '#6693bf' },
    { name: 'Lotus Blue 4',    hex: '#4d699b' },
    { name: 'Lotus Blue 5',    hex: '#5d57a3' },
    { name: 'Lotus Violet 1',  hex: '#a09cac' },
    { name: 'Lotus Violet 2',  hex: '#766b90' },
    { name: 'Lotus Violet 4',  hex: '#624c83' },
    { name: 'Old White',       hex: '#c8c093' },
    { name: 'Fuji White',      hex: '#dcd7ba' },
  ],
});
