WhichTheme.register({
  id: 'kanagawa-wave',
  name: 'Kanagawa Wave',
  group: 'Kanagawa',
  homepage: 'https://github.com/rebelot/kanagawa.nvim',
  preview: {
    bg: '#1f1f28', bg2: '#16161d', text: '#dcd7ba', comment: '#727169',
    keyword: '#957fb8', func: '#7e9cd8', string: '#98bb6c', number: '#d27e99',
    operator: '#7aa89f', type: '#7fb4ca', highlight: '#2a2a37',
  },
  colors: [
    { name: 'Sumiink 0',       hex: '#16161d' },
    { name: 'Sumiink 1',       hex: '#1f1f28' },
    { name: 'Sumiink 2',       hex: '#2a2a37' },
    { name: 'Sumiink 3',       hex: '#363646' },
    { name: 'Sumiink 4',       hex: '#54546d' },
    { name: 'Wave Blue 1',     hex: '#223249' },
    { name: 'Wave Blue 2',     hex: '#2d4f67' },
    { name: 'Old White',       hex: '#c8c093' },
    { name: 'Fuji White',      hex: '#dcd7ba' },
    { name: 'Fuji Gray',       hex: '#727169' },
    { name: 'Spring Green',    hex: '#98bb6c' },
    { name: 'Autumn Green',    hex: '#76946a' },
    { name: 'Wave Aqua 1',     hex: '#6a9589' },
    { name: 'Wave Aqua 2',     hex: '#7aa89f' },
    { name: 'Spring Blue',     hex: '#7fb4ca' },
    { name: 'Crystal Blue',    hex: '#7e9cd8' },
    { name: 'Spring Violet 1', hex: '#938aa9' },
    { name: 'Spring Violet 2', hex: '#9cabca' },
    { name: 'Autumn Yellow',   hex: '#dca561' },
    { name: 'Old Gold',        hex: '#c0a36e' },
    { name: 'Autumn Red',      hex: '#c34043' },
    { name: 'Samurai Red',     hex: '#e82424' },
    { name: 'Surimi Orange',   hex: '#ffa066' },
    { name: 'Ronin Yellow',    hex: '#ff9e3b' },
    { name: 'Sakura Red',      hex: '#e46876' },
    { name: 'Lotus Pink',      hex: '#d27e99' },
    { name: 'Botan',           hex: '#ff5d62' },
    { name: 'Dragon Blue',     hex: '#658594' },
  ],
});
