WhichTheme.register({
  id: 'modus-operandi-tinted',
  name: 'Modus Operandi Tinted',
  group: 'Modus',
  homepage: 'https://protesilaos.com/emacs/modus-themes',
  preview: {
    bg: '#faf6ef', bg2: '#ede8d5', text: '#000000', comment: '#595959',
    keyword: '#721045', func: '#0031a9', string: '#006800', number: '#8b0000',
    operator: '#005e8b', type: '#005a5f', highlight: '#ddd8c8',
  },
  colors: [
    { name: 'Background',      hex: '#faf6ef' },
    { name: 'Background Dim',  hex: '#ede8d5' },
    { name: 'Background Alt',  hex: '#ddd8c8' },
    { name: 'Background Mark', hex: '#c8c3b4' },
    { name: 'Foreground',      hex: '#000000' },
    { name: 'Foreground Dim',  hex: '#595959' },
    { name: 'Red',             hex: '#a60000' },
    { name: 'Red Warmer',      hex: '#972500' },
    { name: 'Red Cooler',      hex: '#a0132f' },
    { name: 'Green',           hex: '#006800' },
    { name: 'Green Warmer',    hex: '#316500' },
    { name: 'Green Cooler',    hex: '#00663f' },
    { name: 'Yellow',          hex: '#6f5500' },
    { name: 'Yellow Warmer',   hex: '#884900' },
    { name: 'Yellow Cooler',   hex: '#7a4f2f' },
    { name: 'Blue',            hex: '#0031a9' },
    { name: 'Blue Warmer',     hex: '#3548cf' },
    { name: 'Blue Cooler',     hex: '#0000b0' },
    { name: 'Magenta',         hex: '#721045' },
    { name: 'Magenta Warmer',  hex: '#8f0075' },
    { name: 'Magenta Cooler',  hex: '#531ab6' },
    { name: 'Cyan',            hex: '#005e8b' },
    { name: 'Cyan Warmer',     hex: '#3f578f' },
    { name: 'Cyan Cooler',     hex: '#005a5f' },
  ],
});
