WhichTheme.register({
  id: 'modus-vivendi-tinted',
  name: 'Modus Vivendi Tinted',
  group: 'Modus',
  homepage: 'https://protesilaos.com/emacs/modus-themes',
  preview: {
    bg: '#0d0d0d', bg2: '#1e1e1e', text: '#fbf8ef', comment: '#989898',
    keyword: '#feacd0', func: '#79a8ff', string: '#79a8ff', number: '#f78fe7',
    operator: '#6ae4b9', type: '#00d3d0', highlight: '#2c2c2c',
  },
  colors: [
    { name: 'Background',      hex: '#0d0d0d' },
    { name: 'Background Dim',  hex: '#1e1e1e' },
    { name: 'Background Alt',  hex: '#2c2c2c' },
    { name: 'Background Mark', hex: '#404040' },
    { name: 'Foreground',      hex: '#fbf8ef' },
    { name: 'Foreground Dim',  hex: '#989898' },
    { name: 'Red',             hex: '#ff8059' },
    { name: 'Red Warmer',      hex: '#ef8b50' },
    { name: 'Red Cooler',      hex: '#ff9077' },
    { name: 'Green',           hex: '#44bc44' },
    { name: 'Green Warmer',    hex: '#70b900' },
    { name: 'Green Cooler',    hex: '#00c06f' },
    { name: 'Yellow',          hex: '#d0bc00' },
    { name: 'Yellow Warmer',   hex: '#fec43f' },
    { name: 'Yellow Cooler',   hex: '#dfaf7a' },
    { name: 'Blue',            hex: '#2fafff' },
    { name: 'Blue Warmer',     hex: '#79a8ff' },
    { name: 'Blue Cooler',     hex: '#00bcff' },
    { name: 'Magenta',         hex: '#feacd0' },
    { name: 'Magenta Warmer',  hex: '#f78fe7' },
    { name: 'Magenta Cooler',  hex: '#b6a0ff' },
    { name: 'Cyan',            hex: '#00d3d0' },
    { name: 'Cyan Warmer',     hex: '#4ae2f0' },
    { name: 'Cyan Cooler',     hex: '#6ae4b9' },
  ],
});
