WhichTheme.register({
  id: 'tokyo-night-dark',
  name: 'Tokyo Night',
  group: 'Tokyo Night',
  homepage: 'https://github.com/folke/tokyonight.nvim',
  preview: {
    bg: '#1a1b26', bg2: '#16161e', text: '#c0caf5', comment: '#565f89',
    keyword: '#bb9af7', func: '#7aa2f7', string: '#9ece6a', number: '#ff9e64',
    operator: '#89ddff', type: '#2ac3de', highlight: '#292e42',
  },
  colors: [
    { name: 'Background',      hex: '#1a1b26' },
    { name: 'Background Dark', hex: '#16161e' },
    { name: 'Highlight',       hex: '#292e42' },
    { name: 'Terminal Black',  hex: '#414868' },
    { name: 'Foreground',      hex: '#c0caf5' },
    { name: 'Comment',         hex: '#565f89' },
    { name: 'Dark5',           hex: '#737aa2' },
    { name: 'Blue',            hex: '#7aa2f7' },
    { name: 'Blue 0',          hex: '#3d59a1' },
    { name: 'Blue 1',          hex: '#2ac3de' },
    { name: 'Blue 2',          hex: '#0db9d7' },
    { name: 'Blue 5',          hex: '#89ddff' },
    { name: 'Blue 6',          hex: '#b4f9f8' },
    { name: 'Blue 7',          hex: '#394b70' },
    { name: 'Magenta',         hex: '#bb9af7' },
    { name: 'Magenta 2',       hex: '#ff007c' },
    { name: 'Purple',          hex: '#9d7cd8' },
    { name: 'Orange',          hex: '#ff9e64' },
    { name: 'Yellow',          hex: '#e0af68' },
    { name: 'Green',           hex: '#9ece6a' },
    { name: 'Green 1',         hex: '#73daca' },
    { name: 'Green 2',         hex: '#41a6b5' },
    { name: 'Teal',            hex: '#1abc9c' },
    { name: 'Red',             hex: '#f7768e' },
    { name: 'Red 1',           hex: '#db4b4b' },
  ],
});
