WhichTheme.register({
  id: 'everforest-dark',
  name: 'Everforest Dark',
  group: 'Everforest',
  homepage: 'https://github.com/sainnhe/everforest',
  preview: {
    bg: '#2d353b', bg2: '#272e33', text: '#d3c6aa', comment: '#859289',
    keyword: '#e67e80', func: '#7fbbb3', string: '#a7c080', number: '#d699b6',
    operator: '#83c092', type: '#dbbc7f', highlight: '#3d484d',
  },
  colors: [
    { name: 'Background',   hex: '#2d353b' },
    { name: 'Bg Hard',      hex: '#272e33' },
    { name: 'Bg Soft',      hex: '#343f44' },
    { name: 'Bg 1',         hex: '#3d484d' },
    { name: 'Bg 2',         hex: '#475258' },
    { name: 'Bg 3',         hex: '#4f585e' },
    { name: 'Bg 4',         hex: '#56635f' },
    { name: 'Grey 0',       hex: '#7a8478' },
    { name: 'Grey 1',       hex: '#859289' },
    { name: 'Grey 2',       hex: '#9da9a0' },
    { name: 'Foreground',   hex: '#d3c6aa' },
    { name: 'Red',          hex: '#e67e80' },
    { name: 'Orange',       hex: '#e69875' },
    { name: 'Yellow',       hex: '#dbbc7f' },
    { name: 'Green',        hex: '#a7c080' },
    { name: 'Aqua',         hex: '#83c092' },
    { name: 'Blue',         hex: '#7fbbb3' },
    { name: 'Purple',       hex: '#d699b6' },
  ],
});
