WhichTheme.register({
  id: 'flexoki-light',
  name: 'Flexoki Light',
  group: 'Flexoki',
  homepage: 'https://github.com/kepano/flexoki',
  preview: {
    bg: '#fffcf0', bg2: '#f2f0e5', text: '#100f0f', comment: '#878580',
    keyword: '#d14d41', func: '#4385be', string: '#879a39', number: '#8b7ec8',
    operator: '#3aa99f', type: '#da702c', highlight: '#e6e4d9',
  },
  colors: [
    { name: 'Paper',        hex: '#fffcf0' },
    { name: 'Base 100',     hex: '#f2f0e5' },
    { name: 'Base 200',     hex: '#e6e4d9' },
    { name: 'Base 300',     hex: '#dad8ce' },
    { name: 'Base 500',     hex: '#b7b5ac' },
    { name: 'Base 600',     hex: '#878580' },
    { name: 'Base 700',     hex: '#6f6e69' },
    { name: 'Base 800',     hex: '#403e3c' },
    { name: 'Black',        hex: '#100f0f' },
    { name: 'Red',          hex: '#af3029' },
    { name: 'Red Bright',   hex: '#d14d41' },
    { name: 'Orange',       hex: '#bc5215' },
    { name: 'Orange Bright', hex: '#da702c' },
    { name: 'Yellow',       hex: '#ad8301' },
    { name: 'Yellow Bright', hex: '#d0a215' },
    { name: 'Green',        hex: '#66800b' },
    { name: 'Green Bright', hex: '#879a39' },
    { name: 'Cyan',         hex: '#24837b' },
    { name: 'Cyan Bright',  hex: '#3aa99f' },
    { name: 'Blue',         hex: '#205ea6' },
    { name: 'Blue Bright',  hex: '#4385be' },
    { name: 'Purple',       hex: '#5e409d' },
    { name: 'Purple Bright', hex: '#8b7ec8' },
    { name: 'Magenta',      hex: '#a02f6f' },
    { name: 'Magenta Bright', hex: '#ce5d97' },
  ],
});
