WhichTheme.register({
  id: 'catppuccin-frappe',
  name: 'Catppuccin Frappé',
  group: 'Catppuccin',
  homepage: 'https://github.com/catppuccin/catppuccin',
  preview: {
    bg: '#303446', bg2: '#292c3c', text: '#c6d0f5', comment: '#737994',
    keyword: '#ca9ee6', func: '#8caaee', string: '#a6d189', number: '#ef9f76',
    operator: '#99d1db', type: '#e5c890', highlight: '#414559',
  },
  colors: [
    { name: 'Rosewater', hex: '#f2d5cf' },
    { name: 'Flamingo',  hex: '#eebebe' },
    { name: 'Pink',      hex: '#f4b8e4' },
    { name: 'Mauve',     hex: '#ca9ee6' },
    { name: 'Red',       hex: '#e78284' },
    { name: 'Maroon',    hex: '#ea999c' },
    { name: 'Peach',     hex: '#ef9f76' },
    { name: 'Yellow',    hex: '#e5c890' },
    { name: 'Green',     hex: '#a6d189' },
    { name: 'Teal',      hex: '#81c8be' },
    { name: 'Sky',       hex: '#99d1db' },
    { name: 'Sapphire',  hex: '#85c1dc' },
    { name: 'Blue',      hex: '#8caaee' },
    { name: 'Lavender',  hex: '#babbf1' },
    { name: 'Text',      hex: '#c6d0f5' },
    { name: 'Subtext 1', hex: '#b5bfe2' },
    { name: 'Subtext 0', hex: '#a5adce' },
    { name: 'Overlay 2', hex: '#949cbb' },
    { name: 'Overlay 1', hex: '#838ba7' },
    { name: 'Overlay 0', hex: '#737994' },
    { name: 'Surface 2', hex: '#626880' },
    { name: 'Surface 1', hex: '#51576d' },
    { name: 'Surface 0', hex: '#414559' },
    { name: 'Base',      hex: '#303446' },
    { name: 'Mantle',    hex: '#292c3c' },
    { name: 'Crust',     hex: '#232634' },
  ],
});
