WhichTheme.register({
  id: 'catppuccin-latte',
  name: 'Catppuccin Latte',
  group: 'Catppuccin',
  homepage: 'https://github.com/catppuccin/catppuccin',
  preview: {
    bg: '#eff1f5', bg2: '#e6e9ef', text: '#4c4f69', comment: '#8c8fa1',
    keyword: '#8839ef', func: '#1e66f5', string: '#40a02b', number: '#fe640b',
    operator: '#04a5e5', type: '#df8e1d', highlight: '#ccd0da',
  },
  colors: [
    { name: 'Rosewater', hex: '#dc8a78' },
    { name: 'Flamingo',  hex: '#dd7878' },
    { name: 'Pink',      hex: '#ea76cb' },
    { name: 'Mauve',     hex: '#8839ef' },
    { name: 'Red',       hex: '#d20f39' },
    { name: 'Maroon',    hex: '#e64553' },
    { name: 'Peach',     hex: '#fe640b' },
    { name: 'Yellow',    hex: '#df8e1d' },
    { name: 'Green',     hex: '#40a02b' },
    { name: 'Teal',      hex: '#179299' },
    { name: 'Sky',       hex: '#04a5e5' },
    { name: 'Sapphire',  hex: '#209fb5' },
    { name: 'Blue',      hex: '#1e66f5' },
    { name: 'Lavender',  hex: '#7287fd' },
    { name: 'Text',      hex: '#4c4f69' },
    { name: 'Subtext 1', hex: '#5c5f77' },
    { name: 'Subtext 0', hex: '#6c6f85' },
    { name: 'Overlay 2', hex: '#7c7f93' },
    { name: 'Overlay 1', hex: '#8c8fa1' },
    { name: 'Overlay 0', hex: '#9ca0b0' },
    { name: 'Surface 2', hex: '#acb0be' },
    { name: 'Surface 1', hex: '#bcc0cc' },
    { name: 'Surface 0', hex: '#ccd0da' },
    { name: 'Base',      hex: '#eff1f5' },
    { name: 'Mantle',    hex: '#e6e9ef' },
    { name: 'Crust',     hex: '#dce0e8' },
  ],
});
