WhichTheme.register({
  id: 'catppuccin-macchiato',
  name: 'Catppuccin Macchiato',
  group: 'Catppuccin',
  homepage: 'https://github.com/catppuccin/catppuccin',
  preview: {
    bg: '#24273a', bg2: '#1e2030', text: '#cad3f5', comment: '#6e738d',
    keyword: '#c6a0f6', func: '#8aadf4', string: '#a6da95', number: '#f5a97f',
    operator: '#91d7e3', type: '#eed49f', highlight: '#363a4f',
  },
  colors: [
    { name: 'Rosewater', hex: '#f4dbd6' },
    { name: 'Flamingo',  hex: '#f0c6c6' },
    { name: 'Pink',      hex: '#f5bde6' },
    { name: 'Mauve',     hex: '#c6a0f6' },
    { name: 'Red',       hex: '#ed8796' },
    { name: 'Maroon',    hex: '#ee99a0' },
    { name: 'Peach',     hex: '#f5a97f' },
    { name: 'Yellow',    hex: '#eed49f' },
    { name: 'Green',     hex: '#a6da95' },
    { name: 'Teal',      hex: '#8bd5ca' },
    { name: 'Sky',       hex: '#91d7e3' },
    { name: 'Sapphire',  hex: '#7dc4e4' },
    { name: 'Blue',      hex: '#8aadf4' },
    { name: 'Lavender',  hex: '#b7bdf8' },
    { name: 'Text',      hex: '#cad3f5' },
    { name: 'Subtext 1', hex: '#b8c0e0' },
    { name: 'Subtext 0', hex: '#a5adcb' },
    { name: 'Overlay 2', hex: '#939ab7' },
    { name: 'Overlay 1', hex: '#8087a2' },
    { name: 'Overlay 0', hex: '#6e738d' },
    { name: 'Surface 2', hex: '#5b6078' },
    { name: 'Surface 1', hex: '#494d64' },
    { name: 'Surface 0', hex: '#363a4f' },
    { name: 'Base',      hex: '#24273a' },
    { name: 'Mantle',    hex: '#1e2030' },
    { name: 'Crust',     hex: '#181926' },
  ],
});
