WhichTheme.register({
  id: 'catppuccin-mocha',
  name: 'Catppuccin Mocha',
  group: 'Catppuccin',
  homepage: 'https://github.com/catppuccin/catppuccin',
  preview: {
    bg: '#1e1e2e', bg2: '#181825', text: '#cdd6f4', comment: '#6c7086',
    keyword: '#cba6f7', func: '#89b4fa', string: '#a6e3a1', number: '#fab387',
    operator: '#89dceb', type: '#f5c2e7', highlight: '#313244',
  },
  colors: [
    { name: 'Rosewater', hex: '#f5e0dc' },
    { name: 'Flamingo',  hex: '#f2cdcd' },
    { name: 'Pink',      hex: '#f5c2e7' },
    { name: 'Mauve',     hex: '#cba6f7' },
    { name: 'Red',       hex: '#f38ba8' },
    { name: 'Maroon',    hex: '#eba0ac' },
    { name: 'Peach',     hex: '#fab387' },
    { name: 'Yellow',    hex: '#f9e2af' },
    { name: 'Green',     hex: '#a6e3a1' },
    { name: 'Teal',      hex: '#94e2d5' },
    { name: 'Sky',       hex: '#89dceb' },
    { name: 'Sapphire',  hex: '#74c7ec' },
    { name: 'Blue',      hex: '#89b4fa' },
    { name: 'Lavender',  hex: '#b4befe' },
    { name: 'Text',      hex: '#cdd6f4' },
    { name: 'Subtext 1', hex: '#bac2de' },
    { name: 'Subtext 0', hex: '#a6adc8' },
    { name: 'Overlay 2', hex: '#9399b2' },
    { name: 'Overlay 1', hex: '#7f849c' },
    { name: 'Overlay 0', hex: '#6c7086' },
    { name: 'Surface 2', hex: '#585b70' },
    { name: 'Surface 1', hex: '#45475a' },
    { name: 'Surface 0', hex: '#313244' },
    { name: 'Base',      hex: '#1e1e2e' },
    { name: 'Mantle',    hex: '#181825' },
    { name: 'Crust',     hex: '#11111b' },
  ],
});
