WhichTheme.register({
  id: 'github-dark',
  name: 'GitHub Dark',
  group: 'GitHub',
  homepage: 'https://github.com/primer/primitives',
  preview: {
    bg: '#0d1117', bg2: '#161b22', text: '#e6edf3', comment: '#8b949e',
    keyword: '#ff7b72', func: '#d2a8ff', string: '#a5d6ff', number: '#79c0ff',
    operator: '#79c0ff', type: '#ffa657', highlight: '#21262d',
  },
  colors: [
    { name: 'Canvas Default',  hex: '#0d1117' },
    { name: 'Canvas Subtle',   hex: '#161b22' },
    { name: 'Canvas Inset',    hex: '#010409' },
    { name: 'Border Default',  hex: '#30363d' },
    { name: 'Border Muted',    hex: '#21262d' },
    { name: 'Foreground',      hex: '#e6edf3' },
    { name: 'Muted',           hex: '#8b949e' },
    { name: 'Red',             hex: '#ff7b72' },
    { name: 'Red Dark',        hex: '#da3633' },
    { name: 'Orange',          hex: '#ffa657' },
    { name: 'Yellow',          hex: '#e3b341' },
    { name: 'Green',           hex: '#3fb950' },
    { name: 'Green Dark',      hex: '#238636' },
    { name: 'Teal',            hex: '#39c5cf' },
    { name: 'Blue',            hex: '#79c0ff' },
    { name: 'Blue Dark',       hex: '#388bfd' },
    { name: 'Purple',          hex: '#d2a8ff' },
    { name: 'Purple Dark',     hex: '#8957e5' },
    { name: 'Pink',            hex: '#f778ba' },
    { name: 'Coral',           hex: '#ff7b72' },
  ],
});
