WhichTheme.register({
  id: 'github-light',
  name: 'GitHub Light',
  group: 'GitHub',
  homepage: 'https://github.com/primer/primitives',
  preview: {
    bg: '#ffffff', bg2: '#f6f8fa', text: '#1f2328', comment: '#6e7781',
    keyword: '#cf222e', func: '#8250df', string: '#0a3069', number: '#0550ae',
    operator: '#0550ae', type: '#953800', highlight: '#eaeef2',
  },
  colors: [
    { name: 'Canvas Default',  hex: '#ffffff' },
    { name: 'Canvas Subtle',   hex: '#f6f8fa' },
    { name: 'Canvas Inset',    hex: '#f0f2f4' },
    { name: 'Border Default',  hex: '#d0d7de' },
    { name: 'Border Muted',    hex: '#d8dee4' },
    { name: 'Foreground',      hex: '#1f2328' },
    { name: 'Muted',           hex: '#656d76' },
    { name: 'Red',             hex: '#cf222e' },
    { name: 'Red Dark',        hex: '#a40e26' },
    { name: 'Orange',          hex: '#bc4c00' },
    { name: 'Yellow',          hex: '#9a6700' },
    { name: 'Green',           hex: '#1a7f37' },
    { name: 'Green Dark',      hex: '#116329' },
    { name: 'Teal',            hex: '#1b7c83' },
    { name: 'Blue',            hex: '#0550ae' },
    { name: 'Blue Dark',       hex: '#0969da' },
    { name: 'Purple',          hex: '#8250df' },
    { name: 'Purple Dark',     hex: '#6e40c9' },
    { name: 'Pink',            hex: '#bf3989' },
    { name: 'Coral',           hex: '#c4432b' },
  ],
});
