WhichTheme.register({
  id: 'oxocarbon-dark',
  name: 'Oxocarbon Dark',
  group: 'Oxocarbon',
  homepage: 'https://github.com/nyoom-engineering/oxocarbon.nvim',
  preview: {
    bg: '#161616', bg2: '#262626', text: '#f2f4f8', comment: '#525252',
    keyword: '#be95ff', func: '#78a9ff', string: '#42be65', number: '#ff832b',
    operator: '#08bdba', type: '#33b1ff', highlight: '#393939',
  },
  colors: [
    { name: 'Background',   hex: '#161616' },
    { name: 'Surface',      hex: '#262626' },
    { name: 'Overlay',      hex: '#393939' },
    { name: 'Subtle',       hex: '#525252' },
    { name: 'Muted',        hex: '#6f6f6f' },
    { name: 'Text',         hex: '#f2f4f8' },
    { name: 'Text Bright',  hex: '#ffffff' },
    { name: 'Red',          hex: '#ff7eb6' },
    { name: 'Orange',       hex: '#ff832b' },
    { name: 'Yellow',       hex: '#f1c21b' },
    { name: 'Green',        hex: '#42be65' },
    { name: 'Teal',         hex: '#08bdba' },
    { name: 'Cyan',         hex: '#33b1ff' },
    { name: 'Blue',         hex: '#78a9ff' },
    { name: 'Purple',       hex: '#be95ff' },
    { name: 'Pink',         hex: '#ff7eb6' },
  ],
});
