WhichTheme.register({
  id: 'oxocarbon-light',
  name: 'Oxocarbon Light',
  group: 'Oxocarbon',
  homepage: 'https://github.com/nyoom-engineering/oxocarbon.nvim',
  preview: {
    bg: '#ffffff', bg2: '#f4f4f4', text: '#161616', comment: '#525252',
    keyword: '#8a3ffc', func: '#0f62fe', string: '#198038', number: '#8a3800',
    operator: '#007d79', type: '#0072c3', highlight: '#e0e0e0',
  },
  colors: [
    { name: 'Background',   hex: '#ffffff' },
    { name: 'Surface',      hex: '#f4f4f4' },
    { name: 'Overlay',      hex: '#e0e0e0' },
    { name: 'Subtle',       hex: '#525252' },
    { name: 'Muted',        hex: '#6f6f6f' },
    { name: 'Text',         hex: '#161616' },
    { name: 'Text Dim',     hex: '#000000' },
    { name: 'Red',          hex: '#da1e28' },
    { name: 'Orange',       hex: '#8a3800' },
    { name: 'Yellow',       hex: '#b28600' },
    { name: 'Green',        hex: '#198038' },
    { name: 'Teal',         hex: '#007d79' },
    { name: 'Cyan',         hex: '#0072c3' },
    { name: 'Blue',         hex: '#0f62fe' },
    { name: 'Purple',       hex: '#8a3ffc' },
    { name: 'Pink',         hex: '#9f1853' },
  ],
});
